module.exports = [
  {
    id: 1,
    producer_id: 1,
    title: "In Da Club",
    name: "ProdLightSalmons",
    caption: "test",
    BPM: "145",
    image_url: "",
    audio_url: "",
  },
  {
    id: 2,
    producer_id: 2,
    title: "Get Crunk",
    name: "NicoleOnDaBeat",
    caption: "test",
    BPM: "160",
    image_url: "",
    audio_url: "",
  },
  {
    id: 3,
    producer_id: 3,
    title: "K#N1!",
    name: "YungMichael",
    caption: "test",
    BPM: "115",
    image_url: "",
    audio_url: "",
  },
  {
    id: 4,
    producer_id: 4,
    title: "Daylight Sonata",
    name: "KARST",
    caption: "test",
    BPM: "70",
    image_url: "",
    audio_url: "",
  },
  {
    id: 5,
    producer_id: 3,
    title: "Banzai",
    name: "YungMichael",
    caption: "test",
    BPM: "140",
    image_url: "",
    audio_url: "",
  },
];
